version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: grandspaceee-dbbq
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: grandspace
    ports:
      - "3709:3306"
    networks:
      - grand_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: grandspaceee-phpmyadminnq
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8088:80"
    networks:
      - grand_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grandspace-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/grandspace?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "9595:9555"
    depends_on:
      - db
    networks:
      - grand_network

networks:
  grand_network:
    driver: bridge
