version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: grandspace-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: grandspace
    ports:
      - "3709:3306"
    networks:
      - grandspace_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: grandspace-phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8088:80"
    networks:
      - grandspace_network

  app:
    build:
      context: .
    container_name: grandspace-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/grandspace?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "9555:9555"
    depends_on:
      - db
    networks:
      - grandspace_network

networks:
  grandspace_network:
